// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2EB-t6KA8EKlNZh0ChWkTp__q3PXiuJ4',
    appId: '1:8897150125:android:12f708826a8e09144d1a24',
    messagingSenderId: '8897150125',
    projectId: 'corvit-fa83d',
    databaseURL: 'https://corvit-fa83d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvit-fa83d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2C_XGhmsmOU9_SwzAd0rRg4_aCC2W8tw',
    appId: '1:8897150125:ios:5e6d2fa0ca0c33204d1a24',
    messagingSenderId: '8897150125',
    projectId: 'corvit-fa83d',
    databaseURL: 'https://corvit-fa83d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvit-fa83d.appspot.com',
    iosClientId: '8897150125-4gev625bd7fncvpda2vqul210if0bl5o.apps.googleusercontent.com',
    iosBundleId: 'com.proglabs.foodapp.corvit',
  );
}
